/*
 * This file is part of rpgm-ai-translator.
 *
 * Copyright (C) 2026 Nikita Fedorov
 *
 * rpgm-ai-translator is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * rpgm-ai-translator is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with rpgm-ai-translator. If not, see <https://www.gnu.org/licenses/>.
 */

import { containsTranslatableLetter } from "../utils/text.js";

export type RpgMakerPlugin = {
  name?: string;
  status?: boolean;
  parameters?: Record<string, unknown>;
  [key: string]: unknown;
};

const PLUGINS_PATH_PATTERN = /^(\d+)\.parameters\.(.+)$/;

export function parsePluginsJs(raw: string): RpgMakerPlugin[] {
  const match = raw.match(/\$plugins\s*=\s*(\[[\s\S]*\])\s*;?\s*$/);
  if (!match) {
    throw new Error("Could not parse plugins.js: missing $plugins array");
  }
  const parsed = JSON.parse(match[1]) as unknown;
  if (!Array.isArray(parsed)) {
    throw new Error("Could not parse plugins.js: $plugins is not an array");
  }
  return parsed as RpgMakerPlugin[];
}

export function serializePluginsJs(plugins: RpgMakerPlugin[]): string {
  return `// Generated by RPG Maker.\n// Do not edit this file directly.\nvar $plugins = ${JSON.stringify(plugins, null, 2)};\n`;
}

// Rewrite only the `$plugins = [...]` array region of an existing plugins.js,
// keeping the file's header comments and surrounding text intact and matching the
// array's original minified-vs-pretty shape, so the patch diff stays minimal.
export function replacePluginsArray(raw: string, plugins: RpgMakerPlugin[]): string {
  const match = raw.match(/(\$plugins\s*=\s*)(\[[\s\S]*\])(\s*;?\s*)$/);
  if (!match || match.index == null) {
    throw new Error("Could not locate $plugins array to rewrite");
  }
  const [, prefix, arrayText] = match;
  const indent = arrayText.includes("\n") ? 2 : undefined;
  const serialized = JSON.stringify(plugins, null, indent);
  const arrayStart = match.index + prefix.length;
  return `${raw.slice(0, arrayStart)}${serialized}${raw.slice(arrayStart + arrayText.length)}`;
}

export function getPluginParameter(plugins: RpgMakerPlugin[], jsonPath: string): string | undefined {
  const parsed = parsePluginParameterPath(jsonPath);
  if (!parsed) {
    return undefined;
  }
  const value = plugins[parsed.pluginIndex]?.parameters?.[parsed.parameterKey];
  return typeof value === "string" ? value : undefined;
}

export function setPluginParameter(plugins: RpgMakerPlugin[], jsonPath: string, value: string): void {
  const parsed = parsePluginParameterPath(jsonPath);
  if (!parsed) {
    throw new Error(`Invalid plugin parameter path '${jsonPath}'`);
  }
  const parameters = plugins[parsed.pluginIndex]?.parameters;
  if (!parameters) {
    throw new Error(`Missing plugin parameters at '${jsonPath}'`);
  }
  parameters[parsed.parameterKey] = value;
}

export function pluginParameterPath(pluginIndex: number, parameterKey: string): string {
  return `${pluginIndex}.parameters.${parameterKey}`;
}

export function isSafeTranslatablePluginParameter(key: string, value: string): boolean {
  const trimmed = value.trim();
  if (trimmed.length === 0 || trimmed.length > 180) {
    return false;
  }
  if (/^(?:true|false|null|undefined)$/i.test(trimmed) || /^-?\d+(?:\.\d+)?$/.test(trimmed)) {
    return false;
  }
  if (/^#[0-9a-f]{3,8}$/i.test(trimmed) || /^[{[]/.test(trimmed)) {
    return false;
  }
  if (/[;$]|=>|\bfunction\b|\bthis\.|\bGraphics\.|\$game[A-Z]/.test(trimmed)) {
    return false;
  }
  if (/[\\/]/.test(trimmed)) {
    return false;
  }

  const technicalKey =
    /(image|picture|file|path|sound|bgm|bgs|color|width|height|position|align|mode|symbol|switch|variable|id|condition|formula|eval|script|code|priority|style|layout|volume|pitch|pan|radius|angle|duration|opacity|font|window|background|size)/i;
  if (technicalKey.test(key)) {
    return false;
  }

  const textKey = /(text|name|label|message|command|headline|title|caption|help|load|shutdown|itemName|optionName)/i;
  if (!textKey.test(key)) {
    return false;
  }

  if (!containsTranslatableLetter(trimmed)) {
    return false;
  }

  return true;
}

function parsePluginParameterPath(jsonPath: string): { pluginIndex: number; parameterKey: string } | undefined {
  const match = jsonPath.match(PLUGINS_PATH_PATTERN);
  if (!match) {
    return undefined;
  }
  return {
    pluginIndex: Number(match[1]),
    parameterKey: match[2]
  };
}
