/*
 * This file is part of rpgm-ai-translator.
 *
 * Copyright (C) 2026 Nikita Fedorov
 *
 * rpgm-ai-translator is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * rpgm-ai-translator is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with rpgm-ai-translator. If not, see <https://www.gnu.org/licenses/>.
 */

import { detectEol } from "../utils/fs.js";
import { isUnsafePathSegment } from "../utils/json-path.js";
import { containsTranslatableLetter } from "../utils/text.js";

export type RpgMakerPlugin = {
  name?: string;
  status?: boolean;
  parameters?: Record<string, unknown>;
  [key: string]: unknown;
};

const PLUGINS_PATH_PATTERN = /^(\d+)\.parameters\.(.+)$/;

export function parsePluginsJs(raw: string): RpgMakerPlugin[] {
  const located = locatePluginsArray(raw);
  if (!located) {
    throw new Error("Could not parse plugins.js: missing $plugins array");
  }
  const parsed = JSON.parse(located.arrayText) as unknown;
  if (!Array.isArray(parsed)) {
    throw new Error("Could not parse plugins.js: $plugins is not an array");
  }
  return parsed as RpgMakerPlugin[];
}

// Locate the `$plugins = [...]` array by scanning balanced brackets from the
// assignment, instead of anchoring on end-of-file. Anchoring dropped (or
// mis-grabbed) the whole file when anything followed the array, such as a trailing
// statement a hand-edited plugins.js sometimes carries. Returns the text before
// the array, the array literal itself, and everything after it.
function locatePluginsArray(raw: string): { prefix: string; arrayText: string; suffix: string } | undefined {
  const assignment = raw.match(/\$plugins\s*=\s*/);
  if (!assignment || assignment.index == null) {
    return undefined;
  }
  const arrayStart = assignment.index + assignment[0].length;
  if (raw[arrayStart] !== "[") {
    return undefined;
  }
  const arrayEnd = scanBalancedArrayEnd(raw, arrayStart);
  if (arrayEnd == null) {
    return undefined;
  }
  return {
    prefix: raw.slice(0, arrayStart),
    arrayText: raw.slice(arrayStart, arrayEnd),
    suffix: raw.slice(arrayEnd)
  };
}

// Returns the index just past the `]` that closes the array opened at `start`,
// honoring double-quoted strings (and their escapes) so a `]` inside a string does
// not end the scan early. Returns undefined if the brackets never balance.
function scanBalancedArrayEnd(raw: string, start: number): number | undefined {
  let depth = 0;
  let inString = false;
  for (let index = start; index < raw.length; index += 1) {
    const char = raw[index];
    if (inString) {
      if (char === "\\") {
        index += 1;
      } else if (char === '"') {
        inString = false;
      }
      continue;
    }
    if (char === '"') {
      inString = true;
    } else if (char === "[") {
      depth += 1;
    } else if (char === "]") {
      depth -= 1;
      if (depth === 0) {
        return index + 1;
      }
    }
  }
  return undefined;
}

export function serializePluginsJs(plugins: RpgMakerPlugin[]): string {
  return `// Generated by RPG Maker.\n// Do not edit this file directly.\nvar $plugins = ${JSON.stringify(plugins, null, 2)};\n`;
}

// Rewrite only the `$plugins = [...]` array region of an existing plugins.js,
// keeping the file's header comments and surrounding text intact and matching the
// array's original minified-vs-pretty shape, so the patch diff stays minimal.
export function replacePluginsArray(raw: string, plugins: RpgMakerPlugin[]): string {
  const located = locatePluginsArray(raw);
  if (!located) {
    throw new Error("Could not locate $plugins array to rewrite");
  }
  const { prefix, arrayText, suffix } = located;
  // Reproduce the array's original indentation (a hand-edited plugins.js may use
  // 4 spaces or tabs) instead of hardcoding 2, so the patch diff stays minimal.
  const indent = detectArrayIndent(arrayText);
  // JSON.stringify emits LF; match the file's dominant EOL so the rewritten
  // array does not introduce mixed line endings into a CRLF plugins.js.
  const eol = detectEol(raw);
  const serializedLf = JSON.stringify(plugins, null, indent);
  const serialized = eol === "\r\n" ? serializedLf.replace(/\n/g, "\r\n") : serializedLf;
  return `${prefix}${serialized}${suffix}`;
}

// Infer the array's per-level indentation from its first indented line, so a
// rewrite reuses the original unit (2 spaces, 4 spaces, or a tab). A string indent
// is used by JSON.stringify per nesting level; undefined keeps a minified array on
// one line.
function detectArrayIndent(arrayText: string): string | number | undefined {
  if (!arrayText.includes("\n")) {
    return undefined;
  }
  const match = arrayText.match(/\n([ \t]+)/);
  return match ? match[1] : 2;
}

export function getPluginParameter(plugins: RpgMakerPlugin[], jsonPath: string): string | undefined {
  const parsed = parsePluginParameterPath(jsonPath);
  if (!parsed) {
    return undefined;
  }
  const value = plugins[parsed.pluginIndex]?.parameters?.[parsed.parameterKey];
  return typeof value === "string" ? value : undefined;
}

export function setPluginParameter(plugins: RpgMakerPlugin[], jsonPath: string, value: string): void {
  const parsed = parsePluginParameterPath(jsonPath);
  if (!parsed) {
    throw new Error(`Invalid plugin parameter path '${jsonPath}'`);
  }
  if (isUnsafePathSegment(parsed.parameterKey)) {
    throw new Error(`Refusing to write unsafe plugin parameter '${parsed.parameterKey}'`);
  }
  const parameters = plugins[parsed.pluginIndex]?.parameters;
  if (!parameters) {
    throw new Error(`Missing plugin parameters at '${jsonPath}'`);
  }
  parameters[parsed.parameterKey] = value;
}

export function pluginParameterPath(pluginIndex: number, parameterKey: string): string {
  return `${pluginIndex}.parameters.${parameterKey}`;
}

export function isSafeTranslatablePluginParameter(key: string, value: string): boolean {
  const trimmed = value.trim();
  if (trimmed.length === 0 || trimmed.length > 180) {
    return false;
  }
  if (/^(?:true|false|null|undefined)$/i.test(trimmed) || /^-?\d+(?:\.\d+)?$/.test(trimmed)) {
    return false;
  }
  if (/^#[0-9a-f]{3,8}$/i.test(trimmed) || /^[{[]/.test(trimmed)) {
    return false;
  }
  if (/[;$]|=>|\bfunction\b|\bthis\.|\bGraphics\.|\$game[A-Z]/.test(trimmed)) {
    return false;
  }
  if (/[\\/]/.test(trimmed)) {
    return false;
  }

  const technicalKey =
    /(image|picture|file|path|sound|bgm|bgs|color|width|height|position|align|mode|symbol|switch|variable|id|condition|formula|eval|script|code|priority|style|layout|volume|pitch|pan|radius|angle|duration|opacity|font|window|background|size)/i;
  if (technicalKey.test(key)) {
    return false;
  }

  const textKey = /(text|name|label|message|command|headline|title|caption|help|load|shutdown|itemName|optionName)/i;
  if (!textKey.test(key)) {
    return false;
  }

  if (!containsTranslatableLetter(trimmed)) {
    return false;
  }

  return true;
}

function parsePluginParameterPath(jsonPath: string): { pluginIndex: number; parameterKey: string } | undefined {
  const match = jsonPath.match(PLUGINS_PATH_PATTERN);
  if (!match) {
    return undefined;
  }
  return {
    pluginIndex: Number(match[1]),
    parameterKey: match[2]
  };
}
