// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins = [
  {
    "name": "SampleMenu",
    "status": true,
    "description": "Synthetic plugin fixture",
    "parameters": {
      "QuestCommandName": "Quest Log",
      "BackgroundImage": "MenuBackground",
      "Enabled": "true"
    }
  }
];
