import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { tmpdir } from "node:os";
import { describe, expect, it } from "vitest";
import { writePatch } from "../src/engines/rpgmaker-mvmz/patch/public-api.js";
import type { TranslationResult, TranslationUnit } from "../src/core/types/public-api.js";

// Byte-order mark, built from its code point so the source file stays plain ASCII.
const BOM = String.fromCharCode(0xfeff);

// Golden regression guard for the patch output format. Any change that alters the
// bytes the writer emits — indentation, BOM, line endings, trailing newline, the
// plugins.js header, or which leaf is touched — fails here, so the P1.1 safety
// work (and anything after it) cannot silently reshape a shipped patch.
describe("patch output golden", () => {
  function unit(overrides: Partial<TranslationUnit> & Pick<TranslationUnit, "id" | "source" | "filePath" | "jsonPath">): TranslationUnit {
    return { engine: "rpgmaker-mz", category: "name", hash: "h", ...overrides };
  }
  function translate(target: TranslationUnit, translation: string): TranslationResult {
    return { id: target.id, source: target.source, translation, provider: "manual", model: "manual", status: "translated" };
  }

  it("preserves indentation, BOM, line endings and the plugins.js header byte-for-byte", async () => {
    const root = path.join(tmpdir(), `rpgm-golden-${Date.now()}`);
    const outDir = path.join(tmpdir(), `rpgm-golden-out-${Date.now()}`);
    await mkdir(path.join(root, "data"), { recursive: true });
    await mkdir(path.join(root, "js"), { recursive: true });

    // 1. Pretty-printed, LF, trailing newline (the common MV/MZ export).
    const itemsSource = `${JSON.stringify([null, { id: 1, name: "Potion", description: "Restores HP." }], null, 2)}\n`;
    await writeFile(path.join(root, "data", "Items.json"), itemsSource, "utf8");

    // 2. Minified, no trailing newline (as RPG Maker ships data files).
    const actorsSource = JSON.stringify([null, { id: 1, name: "Aria" }]);
    await writeFile(path.join(root, "data", "Actors.json"), actorsSource, "utf8");

    // 3. BOM + CRLF + 2-space indent + trailing newline (a Windows-saved file).
    const systemSource = BOM + JSON.stringify({ gameTitle: "My Game" }, null, 2).replace(/\n/g, "\r\n") + "\r\n";
    await writeFile(path.join(root, "data", "System.json"), systemSource, "utf8");

    // 4. plugins.js with a header comment and a translatable parameter.
    const pluginsSource = `// Generated by RPG Maker.\nvar $plugins = ${JSON.stringify([
      { name: "MenuPlugin", status: true, parameters: { Label: "Quest Log" } }
    ])};\n`;
    await writeFile(path.join(root, "js", "plugins.js"), pluginsSource, "utf8");

    const items = unit({ id: "Items.1.description", source: "Restores HP.", filePath: "data/Items.json", jsonPath: "1.description", category: "description" });
    const actor = unit({ id: "Actors.1.name", source: "Aria", filePath: "data/Actors.json", jsonPath: "1.name" });
    const system = unit({ id: "System.gameTitle", source: "My Game", filePath: "data/System.json", jsonPath: "gameTitle", category: "system" });
    const plugin = unit({ id: "plugins.0.parameters.Label", source: "Quest Log", filePath: "js/plugins.js", jsonPath: "0.parameters.Label", category: "plugin-parameter" });

    const result = await writePatch(
      root,
      [items, actor, system, plugin],
      [
        translate(items, "Восстанавливает ОЗ."),
        translate(actor, "Ария"),
        translate(system, "Моя игра"),
        translate(plugin, "Журнал заданий")
      ],
      { mode: "patch", outDir }
    );
    expect(result.unitsApplied).toBe(4);

    // --- Golden byte-for-byte expectations ---
    const expectedItems = `${JSON.stringify([null, { id: 1, name: "Potion", description: "Восстанавливает ОЗ." }], null, 2)}\n`;
    const expectedActors = JSON.stringify([null, { id: 1, name: "Ария" }]);
    const expectedSystem = BOM + JSON.stringify({ gameTitle: "Моя игра" }, null, 2).replace(/\n/g, "\r\n") + "\r\n";
    const expectedPlugins = `// Generated by RPG Maker.\nvar $plugins = ${JSON.stringify([
      { name: "MenuPlugin", status: true, parameters: { Label: "Журнал заданий" } }
    ])};\n`;

    expect(await readFile(path.join(outDir, "data", "Items.json"), "utf8")).toBe(expectedItems);
    expect(await readFile(path.join(outDir, "data", "Actors.json"), "utf8")).toBe(expectedActors);
    expect(await readFile(path.join(outDir, "data", "System.json"), "utf8")).toBe(expectedSystem);
    expect(await readFile(path.join(outDir, "js", "plugins.js"), "utf8")).toBe(expectedPlugins);

    // The original game files are never modified.
    expect(await readFile(path.join(root, "data", "Items.json"), "utf8")).toBe(itemsSource);
    expect(await readFile(path.join(root, "data", "Actors.json"), "utf8")).toBe(actorsSource);
    expect(await readFile(path.join(root, "data", "System.json"), "utf8")).toBe(systemSource);
    expect(await readFile(path.join(root, "js", "plugins.js"), "utf8")).toBe(pluginsSource);
  });
});
